INSERT INTO public.CATEGORY( ID, NAME, REFRACTION, ID_TOP_CATEGORY)  VALUES (	1	,'Moda',	1	,	null	);
INSERT INTO public.CATEGORY( ID, NAME, REFRACTION, ID_TOP_CATEGORY)  VALUES (	2	,'Elektronik',	1	,	null	);
INSERT INTO public.CATEGORY( ID, NAME, REFRACTION, ID_TOP_CATEGORY)  VALUES (	3	,'Ev & Yaşam',	1	,	null	);
INSERT INTO public.CATEGORY( ID, NAME, REFRACTION, ID_TOP_CATEGORY)  VALUES (	4	,'Elbise',	2	,	1	);
INSERT INTO public.CATEGORY( ID, NAME, REFRACTION, ID_TOP_CATEGORY)  VALUES (	5	,'Gömlek',	2	,	1	);
INSERT INTO public.CATEGORY( ID, NAME, REFRACTION, ID_TOP_CATEGORY)  VALUES (	6	,'Bilgisayar',	2	,	2	);
INSERT INTO public.CATEGORY( ID, NAME, REFRACTION, ID_TOP_CATEGORY)  VALUES (	7	,'Dizüstü Bilgisayar',	3	,	6	);
INSERT INTO public.CATEGORY( ID, NAME, REFRACTION, ID_TOP_CATEGORY)  VALUES (	8	,'Mobilya',	2	,	3	);
INSERT INTO public.CATEGORY( ID, NAME, REFRACTION, ID_TOP_CATEGORY)  VALUES (	9	,'Sehpa',	3	,	8	);

INSERT INTO public.PRODUCT( ID, NAME, PRICE, REGISTER_DATE, ID_CATEGORY) VALUES (	1	,'Mavi Elbise',	200	, now(), 	4);
INSERT INTO public.PRODUCT( ID, NAME, PRICE, REGISTER_DATE, ID_CATEGORY) VALUES (	2	,'Kırmızı Elbise',	300	, now(), 	4);
INSERT INTO public.PRODUCT( ID, NAME, PRICE, REGISTER_DATE, ID_CATEGORY) VALUES (	3	,'Mavi Gömlek',	500	, now(), 	5);
INSERT INTO public.PRODUCT( ID, NAME, PRICE, REGISTER_DATE, ID_CATEGORY) VALUES (	4	,'Sarı Gömlek',	450	, now(), 	5);
INSERT INTO public.PRODUCT( ID, NAME, PRICE, REGISTER_DATE, ID_CATEGORY) VALUES (	5	,'HP ',	15000	, now(), 	7);
INSERT INTO public.PRODUCT( ID, NAME, PRICE, REGISTER_DATE, ID_CATEGORY) VALUES (	6	,'MSI',	20000	, now(), 	7);
INSERT INTO public.PRODUCT( ID, NAME, PRICE, REGISTER_DATE, ID_CATEGORY) VALUES (	7	,'Orta Sehpa',	600	, now(),
